// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/third_party_perception/proto/radar_obstacle.proto

#ifndef PROTOBUF_modules_2fthird_5fparty_5fperception_2fproto_2fradar_5fobstacle_2eproto__INCLUDED
#define PROTOBUF_modules_2fthird_5fparty_5fperception_2fproto_2fradar_5fobstacle_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "modules/common/proto/error_code.pb.h"
#include "modules/common/proto/header.pb.h"
#include "modules/perception/proto/perception_obstacle.pb.h"
// @@protoc_insertion_point(includes)
namespace apollo {
namespace common {
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class StatusPb;
class StatusPbDefaultTypeInternal;
extern StatusPbDefaultTypeInternal _StatusPb_default_instance_;
}  // namespace common
namespace perception {
class PerceptionObstacle;
class PerceptionObstacleDefaultTypeInternal;
extern PerceptionObstacleDefaultTypeInternal _PerceptionObstacle_default_instance_;
class PerceptionObstacles;
class PerceptionObstaclesDefaultTypeInternal;
extern PerceptionObstaclesDefaultTypeInternal _PerceptionObstacles_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
}  // namespace perception
namespace third_party_perception {
class RadarObstacle;
class RadarObstacleDefaultTypeInternal;
extern RadarObstacleDefaultTypeInternal _RadarObstacle_default_instance_;
class RadarObstacles;
class RadarObstaclesDefaultTypeInternal;
extern RadarObstaclesDefaultTypeInternal _RadarObstacles_default_instance_;
class RadarObstacles_RadarObstacleEntry;
class RadarObstacles_RadarObstacleEntryDefaultTypeInternal;
extern RadarObstacles_RadarObstacleEntryDefaultTypeInternal _RadarObstacles_RadarObstacleEntry_default_instance_;
}  // namespace third_party_perception
}  // namespace apollo

namespace apollo {
namespace third_party_perception {

namespace protobuf_modules_2fthird_5fparty_5fperception_2fproto_2fradar_5fobstacle_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_modules_2fthird_5fparty_5fperception_2fproto_2fradar_5fobstacle_2eproto

// ===================================================================

class RadarObstacle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.third_party_perception.RadarObstacle) */ {
 public:
  RadarObstacle();
  virtual ~RadarObstacle();

  RadarObstacle(const RadarObstacle& from);

  inline RadarObstacle& operator=(const RadarObstacle& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarObstacle& default_instance();

  static inline const RadarObstacle* internal_default_instance() {
    return reinterpret_cast<const RadarObstacle*>(
               &_RadarObstacle_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RadarObstacle* other);

  // implements Message ----------------------------------------------

  inline RadarObstacle* New() const PROTOBUF_FINAL { return New(NULL); }

  RadarObstacle* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RadarObstacle& from);
  void MergeFrom(const RadarObstacle& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RadarObstacle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.perception.Point relative_position = 2;
  bool has_relative_position() const;
  void clear_relative_position();
  static const int kRelativePositionFieldNumber = 2;
  const ::apollo::perception::Point& relative_position() const;
  ::apollo::perception::Point* mutable_relative_position();
  ::apollo::perception::Point* release_relative_position();
  void set_allocated_relative_position(::apollo::perception::Point* relative_position);

  // optional .apollo.perception.Point relative_velocity = 3;
  bool has_relative_velocity() const;
  void clear_relative_velocity();
  static const int kRelativeVelocityFieldNumber = 3;
  const ::apollo::perception::Point& relative_velocity() const;
  ::apollo::perception::Point* mutable_relative_velocity();
  ::apollo::perception::Point* release_relative_velocity();
  void set_allocated_relative_velocity(::apollo::perception::Point* relative_velocity);

  // optional .apollo.perception.Point absolute_position = 10;
  bool has_absolute_position() const;
  void clear_absolute_position();
  static const int kAbsolutePositionFieldNumber = 10;
  const ::apollo::perception::Point& absolute_position() const;
  ::apollo::perception::Point* mutable_absolute_position();
  ::apollo::perception::Point* release_absolute_position();
  void set_allocated_absolute_position(::apollo::perception::Point* absolute_position);

  // optional .apollo.perception.Point absolute_velocity = 11;
  bool has_absolute_velocity() const;
  void clear_absolute_velocity();
  static const int kAbsoluteVelocityFieldNumber = 11;
  const ::apollo::perception::Point& absolute_velocity() const;
  ::apollo::perception::Point* mutable_absolute_velocity();
  ::apollo::perception::Point* release_absolute_velocity();
  void set_allocated_absolute_velocity(::apollo::perception::Point* absolute_velocity);

  // optional int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // optional bool movable = 5;
  bool has_movable() const;
  void clear_movable();
  static const int kMovableFieldNumber = 5;
  bool movable() const;
  void set_movable(bool value);

  // optional double rcs = 4;
  bool has_rcs() const;
  void clear_rcs();
  static const int kRcsFieldNumber = 4;
  double rcs() const;
  void set_rcs(double value);

  // optional double width = 6;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 6;
  double width() const;
  void set_width(double value);

  // optional double length = 7;
  bool has_length() const;
  void clear_length();
  static const int kLengthFieldNumber = 7;
  double length() const;
  void set_length(double value);

  // optional double height = 8;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 8;
  double height() const;
  void set_height(double value);

  // optional double theta = 9;
  bool has_theta() const;
  void clear_theta();
  static const int kThetaFieldNumber = 9;
  double theta() const;
  void set_theta(double value);

  // optional int32 count = 12;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 12;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // optional int32 moving_frames_count = 13;
  bool has_moving_frames_count() const;
  void clear_moving_frames_count();
  static const int kMovingFramesCountFieldNumber = 13;
  ::google::protobuf::int32 moving_frames_count() const;
  void set_moving_frames_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:apollo.third_party_perception.RadarObstacle)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_relative_position();
  void clear_has_relative_position();
  void set_has_relative_velocity();
  void clear_has_relative_velocity();
  void set_has_rcs();
  void clear_has_rcs();
  void set_has_movable();
  void clear_has_movable();
  void set_has_width();
  void clear_has_width();
  void set_has_length();
  void clear_has_length();
  void set_has_height();
  void clear_has_height();
  void set_has_theta();
  void clear_has_theta();
  void set_has_absolute_position();
  void clear_has_absolute_position();
  void set_has_absolute_velocity();
  void clear_has_absolute_velocity();
  void set_has_count();
  void clear_has_count();
  void set_has_moving_frames_count();
  void clear_has_moving_frames_count();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::apollo::perception::Point* relative_position_;
  ::apollo::perception::Point* relative_velocity_;
  ::apollo::perception::Point* absolute_position_;
  ::apollo::perception::Point* absolute_velocity_;
  ::google::protobuf::int32 id_;
  bool movable_;
  double rcs_;
  double width_;
  double length_;
  double height_;
  double theta_;
  ::google::protobuf::int32 count_;
  ::google::protobuf::int32 moving_frames_count_;
  friend struct protobuf_modules_2fthird_5fparty_5fperception_2fproto_2fradar_5fobstacle_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class RadarObstacles : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.third_party_perception.RadarObstacles) */ {
 public:
  RadarObstacles();
  virtual ~RadarObstacles();

  RadarObstacles(const RadarObstacles& from);

  inline RadarObstacles& operator=(const RadarObstacles& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarObstacles& default_instance();

  static inline const RadarObstacles* internal_default_instance() {
    return reinterpret_cast<const RadarObstacles*>(
               &_RadarObstacles_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(RadarObstacles* other);

  // implements Message ----------------------------------------------

  inline RadarObstacles* New() const PROTOBUF_FINAL { return New(NULL); }

  RadarObstacles* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RadarObstacles& from);
  void MergeFrom(const RadarObstacles& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RadarObstacles* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .apollo.third_party_perception.RadarObstacle> radar_obstacle = 1;
  int radar_obstacle_size() const;
  void clear_radar_obstacle();
  static const int kRadarObstacleFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::apollo::third_party_perception::RadarObstacle >&
      radar_obstacle() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::apollo::third_party_perception::RadarObstacle >*
      mutable_radar_obstacle();

  // optional .apollo.common.Header header = 2;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 2;
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* mutable_header();
  ::apollo::common::Header* release_header();
  void set_allocated_header(::apollo::common::Header* header);

  // optional .apollo.common.ErrorCode error_code = 3 [default = OK];
  bool has_error_code() const;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 3;
  ::apollo::common::ErrorCode error_code() const;
  void set_error_code(::apollo::common::ErrorCode value);

  // @@protoc_insertion_point(class_scope:apollo.third_party_perception.RadarObstacles)
 private:
  void set_has_header();
  void clear_has_header();
  void set_has_error_code();
  void clear_has_error_code();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  public:
  class RadarObstacles_RadarObstacleEntry : public ::google::protobuf::internal::MapEntry<RadarObstacles_RadarObstacleEntry, 
      ::google::protobuf::int32, ::apollo::third_party_perception::RadarObstacle,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<RadarObstacles_RadarObstacleEntry, 
      ::google::protobuf::int32, ::apollo::third_party_perception::RadarObstacle,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > SuperType;
    RadarObstacles_RadarObstacleEntry();
    RadarObstacles_RadarObstacleEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const RadarObstacles_RadarObstacleEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_RadarObstacles_RadarObstacleEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  ::google::protobuf::internal::MapField<
      RadarObstacles_RadarObstacleEntry,
      ::google::protobuf::int32, ::apollo::third_party_perception::RadarObstacle,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > radar_obstacle_;
  private:
  ::apollo::common::Header* header_;
  int error_code_;
  friend struct protobuf_modules_2fthird_5fparty_5fperception_2fproto_2fradar_5fobstacle_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RadarObstacle

// optional int32 id = 1;
inline bool RadarObstacle::has_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RadarObstacle::set_has_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RadarObstacle::clear_has_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RadarObstacle::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 RadarObstacle::id() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.id)
  return id_;
}
inline void RadarObstacle::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.id)
}

// optional .apollo.perception.Point relative_position = 2;
inline bool RadarObstacle::has_relative_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RadarObstacle::set_has_relative_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RadarObstacle::clear_has_relative_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RadarObstacle::clear_relative_position() {
  if (relative_position_ != NULL) relative_position_->::apollo::perception::Point::Clear();
  clear_has_relative_position();
}
inline const ::apollo::perception::Point& RadarObstacle::relative_position() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.relative_position)
  return relative_position_ != NULL ? *relative_position_
                         : *::apollo::perception::Point::internal_default_instance();
}
inline ::apollo::perception::Point* RadarObstacle::mutable_relative_position() {
  set_has_relative_position();
  if (relative_position_ == NULL) {
    relative_position_ = new ::apollo::perception::Point;
  }
  // @@protoc_insertion_point(field_mutable:apollo.third_party_perception.RadarObstacle.relative_position)
  return relative_position_;
}
inline ::apollo::perception::Point* RadarObstacle::release_relative_position() {
  // @@protoc_insertion_point(field_release:apollo.third_party_perception.RadarObstacle.relative_position)
  clear_has_relative_position();
  ::apollo::perception::Point* temp = relative_position_;
  relative_position_ = NULL;
  return temp;
}
inline void RadarObstacle::set_allocated_relative_position(::apollo::perception::Point* relative_position) {
  delete relative_position_;
  relative_position_ = relative_position;
  if (relative_position) {
    set_has_relative_position();
  } else {
    clear_has_relative_position();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.third_party_perception.RadarObstacle.relative_position)
}

// optional .apollo.perception.Point relative_velocity = 3;
inline bool RadarObstacle::has_relative_velocity() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RadarObstacle::set_has_relative_velocity() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RadarObstacle::clear_has_relative_velocity() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RadarObstacle::clear_relative_velocity() {
  if (relative_velocity_ != NULL) relative_velocity_->::apollo::perception::Point::Clear();
  clear_has_relative_velocity();
}
inline const ::apollo::perception::Point& RadarObstacle::relative_velocity() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.relative_velocity)
  return relative_velocity_ != NULL ? *relative_velocity_
                         : *::apollo::perception::Point::internal_default_instance();
}
inline ::apollo::perception::Point* RadarObstacle::mutable_relative_velocity() {
  set_has_relative_velocity();
  if (relative_velocity_ == NULL) {
    relative_velocity_ = new ::apollo::perception::Point;
  }
  // @@protoc_insertion_point(field_mutable:apollo.third_party_perception.RadarObstacle.relative_velocity)
  return relative_velocity_;
}
inline ::apollo::perception::Point* RadarObstacle::release_relative_velocity() {
  // @@protoc_insertion_point(field_release:apollo.third_party_perception.RadarObstacle.relative_velocity)
  clear_has_relative_velocity();
  ::apollo::perception::Point* temp = relative_velocity_;
  relative_velocity_ = NULL;
  return temp;
}
inline void RadarObstacle::set_allocated_relative_velocity(::apollo::perception::Point* relative_velocity) {
  delete relative_velocity_;
  relative_velocity_ = relative_velocity;
  if (relative_velocity) {
    set_has_relative_velocity();
  } else {
    clear_has_relative_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.third_party_perception.RadarObstacle.relative_velocity)
}

// optional double rcs = 4;
inline bool RadarObstacle::has_rcs() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RadarObstacle::set_has_rcs() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RadarObstacle::clear_has_rcs() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RadarObstacle::clear_rcs() {
  rcs_ = 0;
  clear_has_rcs();
}
inline double RadarObstacle::rcs() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.rcs)
  return rcs_;
}
inline void RadarObstacle::set_rcs(double value) {
  set_has_rcs();
  rcs_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.rcs)
}

// optional bool movable = 5;
inline bool RadarObstacle::has_movable() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RadarObstacle::set_has_movable() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RadarObstacle::clear_has_movable() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RadarObstacle::clear_movable() {
  movable_ = false;
  clear_has_movable();
}
inline bool RadarObstacle::movable() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.movable)
  return movable_;
}
inline void RadarObstacle::set_movable(bool value) {
  set_has_movable();
  movable_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.movable)
}

// optional double width = 6;
inline bool RadarObstacle::has_width() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RadarObstacle::set_has_width() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RadarObstacle::clear_has_width() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RadarObstacle::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline double RadarObstacle::width() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.width)
  return width_;
}
inline void RadarObstacle::set_width(double value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.width)
}

// optional double length = 7;
inline bool RadarObstacle::has_length() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RadarObstacle::set_has_length() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RadarObstacle::clear_has_length() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RadarObstacle::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline double RadarObstacle::length() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.length)
  return length_;
}
inline void RadarObstacle::set_length(double value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.length)
}

// optional double height = 8;
inline bool RadarObstacle::has_height() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RadarObstacle::set_has_height() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RadarObstacle::clear_has_height() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RadarObstacle::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline double RadarObstacle::height() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.height)
  return height_;
}
inline void RadarObstacle::set_height(double value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.height)
}

// optional double theta = 9;
inline bool RadarObstacle::has_theta() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void RadarObstacle::set_has_theta() {
  _has_bits_[0] |= 0x00000400u;
}
inline void RadarObstacle::clear_has_theta() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void RadarObstacle::clear_theta() {
  theta_ = 0;
  clear_has_theta();
}
inline double RadarObstacle::theta() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.theta)
  return theta_;
}
inline void RadarObstacle::set_theta(double value) {
  set_has_theta();
  theta_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.theta)
}

// optional .apollo.perception.Point absolute_position = 10;
inline bool RadarObstacle::has_absolute_position() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RadarObstacle::set_has_absolute_position() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RadarObstacle::clear_has_absolute_position() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RadarObstacle::clear_absolute_position() {
  if (absolute_position_ != NULL) absolute_position_->::apollo::perception::Point::Clear();
  clear_has_absolute_position();
}
inline const ::apollo::perception::Point& RadarObstacle::absolute_position() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.absolute_position)
  return absolute_position_ != NULL ? *absolute_position_
                         : *::apollo::perception::Point::internal_default_instance();
}
inline ::apollo::perception::Point* RadarObstacle::mutable_absolute_position() {
  set_has_absolute_position();
  if (absolute_position_ == NULL) {
    absolute_position_ = new ::apollo::perception::Point;
  }
  // @@protoc_insertion_point(field_mutable:apollo.third_party_perception.RadarObstacle.absolute_position)
  return absolute_position_;
}
inline ::apollo::perception::Point* RadarObstacle::release_absolute_position() {
  // @@protoc_insertion_point(field_release:apollo.third_party_perception.RadarObstacle.absolute_position)
  clear_has_absolute_position();
  ::apollo::perception::Point* temp = absolute_position_;
  absolute_position_ = NULL;
  return temp;
}
inline void RadarObstacle::set_allocated_absolute_position(::apollo::perception::Point* absolute_position) {
  delete absolute_position_;
  absolute_position_ = absolute_position;
  if (absolute_position) {
    set_has_absolute_position();
  } else {
    clear_has_absolute_position();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.third_party_perception.RadarObstacle.absolute_position)
}

// optional .apollo.perception.Point absolute_velocity = 11;
inline bool RadarObstacle::has_absolute_velocity() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RadarObstacle::set_has_absolute_velocity() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RadarObstacle::clear_has_absolute_velocity() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RadarObstacle::clear_absolute_velocity() {
  if (absolute_velocity_ != NULL) absolute_velocity_->::apollo::perception::Point::Clear();
  clear_has_absolute_velocity();
}
inline const ::apollo::perception::Point& RadarObstacle::absolute_velocity() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.absolute_velocity)
  return absolute_velocity_ != NULL ? *absolute_velocity_
                         : *::apollo::perception::Point::internal_default_instance();
}
inline ::apollo::perception::Point* RadarObstacle::mutable_absolute_velocity() {
  set_has_absolute_velocity();
  if (absolute_velocity_ == NULL) {
    absolute_velocity_ = new ::apollo::perception::Point;
  }
  // @@protoc_insertion_point(field_mutable:apollo.third_party_perception.RadarObstacle.absolute_velocity)
  return absolute_velocity_;
}
inline ::apollo::perception::Point* RadarObstacle::release_absolute_velocity() {
  // @@protoc_insertion_point(field_release:apollo.third_party_perception.RadarObstacle.absolute_velocity)
  clear_has_absolute_velocity();
  ::apollo::perception::Point* temp = absolute_velocity_;
  absolute_velocity_ = NULL;
  return temp;
}
inline void RadarObstacle::set_allocated_absolute_velocity(::apollo::perception::Point* absolute_velocity) {
  delete absolute_velocity_;
  absolute_velocity_ = absolute_velocity;
  if (absolute_velocity) {
    set_has_absolute_velocity();
  } else {
    clear_has_absolute_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.third_party_perception.RadarObstacle.absolute_velocity)
}

// optional int32 count = 12;
inline bool RadarObstacle::has_count() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void RadarObstacle::set_has_count() {
  _has_bits_[0] |= 0x00000800u;
}
inline void RadarObstacle::clear_has_count() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void RadarObstacle::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::google::protobuf::int32 RadarObstacle::count() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.count)
  return count_;
}
inline void RadarObstacle::set_count(::google::protobuf::int32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.count)
}

// optional int32 moving_frames_count = 13;
inline bool RadarObstacle::has_moving_frames_count() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void RadarObstacle::set_has_moving_frames_count() {
  _has_bits_[0] |= 0x00001000u;
}
inline void RadarObstacle::clear_has_moving_frames_count() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void RadarObstacle::clear_moving_frames_count() {
  moving_frames_count_ = 0;
  clear_has_moving_frames_count();
}
inline ::google::protobuf::int32 RadarObstacle::moving_frames_count() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacle.moving_frames_count)
  return moving_frames_count_;
}
inline void RadarObstacle::set_moving_frames_count(::google::protobuf::int32 value) {
  set_has_moving_frames_count();
  moving_frames_count_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacle.moving_frames_count)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RadarObstacles

// map<int32, .apollo.third_party_perception.RadarObstacle> radar_obstacle = 1;
inline int RadarObstacles::radar_obstacle_size() const {
  return radar_obstacle_.size();
}
inline void RadarObstacles::clear_radar_obstacle() {
  radar_obstacle_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::apollo::third_party_perception::RadarObstacle >&
RadarObstacles::radar_obstacle() const {
  // @@protoc_insertion_point(field_map:apollo.third_party_perception.RadarObstacles.radar_obstacle)
  return radar_obstacle_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::apollo::third_party_perception::RadarObstacle >*
RadarObstacles::mutable_radar_obstacle() {
  // @@protoc_insertion_point(field_mutable_map:apollo.third_party_perception.RadarObstacles.radar_obstacle)
  return radar_obstacle_.MutableMap();
}

// optional .apollo.common.Header header = 2;
inline bool RadarObstacles::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RadarObstacles::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RadarObstacles::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RadarObstacles::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& RadarObstacles::header() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacles.header)
  return header_ != NULL ? *header_
                         : *::apollo::common::Header::internal_default_instance();
}
inline ::apollo::common::Header* RadarObstacles::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::apollo::common::Header;
  }
  // @@protoc_insertion_point(field_mutable:apollo.third_party_perception.RadarObstacles.header)
  return header_;
}
inline ::apollo::common::Header* RadarObstacles::release_header() {
  // @@protoc_insertion_point(field_release:apollo.third_party_perception.RadarObstacles.header)
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void RadarObstacles::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.third_party_perception.RadarObstacles.header)
}

// optional .apollo.common.ErrorCode error_code = 3 [default = OK];
inline bool RadarObstacles::has_error_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RadarObstacles::set_has_error_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RadarObstacles::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RadarObstacles::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::apollo::common::ErrorCode RadarObstacles::error_code() const {
  // @@protoc_insertion_point(field_get:apollo.third_party_perception.RadarObstacles.error_code)
  return static_cast< ::apollo::common::ErrorCode >(error_code_);
}
inline void RadarObstacles::set_error_code(::apollo::common::ErrorCode value) {
  assert(::apollo::common::ErrorCode_IsValid(value));
  set_has_error_code();
  error_code_ = value;
  // @@protoc_insertion_point(field_set:apollo.third_party_perception.RadarObstacles.error_code)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace third_party_perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2fthird_5fparty_5fperception_2fproto_2fradar_5fobstacle_2eproto__INCLUDED
